// Spell: spice-sim (wild school) — Argos runs circuit simulations.
// Writes SPICE netlists and runs ngspice.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type Input struct {
	Path string            `json:"path"`
	Args map[string]string `json:"args"`
}

type Output struct {
	Summary string `json:"summary"`
	Error   string `json:"error,omitempty"`
}

func main() {
	var in Input
	if err := json.NewDecoder(os.Stdin).Decode(&in); err != nil {
		json.NewEncoder(os.Stdout).Encode(Output{Error: fmt.Sprintf("reading input: %v", err)})
		return
	}
	action := in.Args["action"]
	circuitType := in.Args["circuit_type"]
	analysis := in.Args["analysis"]
	if analysis == "" { analysis = "tran" }
	dir := in.Path
	if dir == "" { dir = "/tmp/argos_spice" }
	os.MkdirAll(dir, 0755)

	switch action {
	case "netlist":
		name := in.Args["name"]
		if name == "" { name = "circuit" }
		netlist := generateNetlist(circuitType, name, in.Args)
		netlistFile := filepath.Join(dir, name+".cir")
		if err := os.WriteFile(netlistFile, []byte(netlist), 0644); err != nil {
			json.NewEncoder(os.Stdout).Encode(Output{Error: err.Error()})
			return
		}
		json.NewEncoder(os.Stdout).Encode(Output{Summary: fmt.Sprintf("wrote netlist to %s", netlistFile)})

	case "simulate":
		name := in.Args["name"]
		if name == "" { name = "circuit" }
		netlistFile := filepath.Join(dir, name+".cir")
		if _, err := os.Stat(netlistFile); os.IsNotExist(err) {
			// Auto-generate if not exists
			netlist := generateNetlist(circuitType, name, in.Args)
			os.WriteFile(netlistFile, []byte(netlist), 0644)
		}
		cmd := exec.Command("ngspice", "-b", netlistFile)
		if out, err := cmd.CombinedOutput(); err != nil {
			json.NewEncoder(os.Stdout).Encode(Output{Error: fmt.Sprintf("%s: %s", err, string(out))})
			return
		}
		json.NewEncoder(os.Stdout).Encode(Output{Summary: fmt.Sprintf("simulated %s (%s analysis)", name, analysis)})

	case "analyze":
		name := in.Args["name"]
		if name == "" { name = "circuit" }
		netlistFile := filepath.Join(dir, name+".cir")
		if _, err := os.Stat(netlistFile); os.IsNotExist(err) {
			netlist := generateNetlist(circuitType, name, in.Args)
			os.WriteFile(netlistFile, []byte(netlist), 0644)
		}
		cmd := exec.Command("ngspice", "-b", netlistFile)
		out, err := cmd.CombinedOutput()
		if err != nil {
			json.NewEncoder(os.Stdout).Encode(Output{Error: fmt.Sprintf("%s: %s", err, string(out))})
			return
		}
		lines := strings.Split(string(out), "\n")
		summary := fmt.Sprintf("simulated %s: %d lines output", name, len(lines))
		for _, l := range lines {
			if strings.Contains(l, "frequency") || strings.Contains(l, "voltage") || strings.Contains(l, "current") {
				summary += "\n" + l
			}
		}
		json.NewEncoder(os.Stdout).Encode(Output{Summary: summary})

	default:
		json.NewEncoder(os.Stdout).Encode(Output{Error: fmt.Sprintf("unknown action: %s", action)})
	}
}

func generateNetlist(circuitType, name string, args map[string]string) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("* %s - generated by Argos\n", name))
	b.WriteString(fmt.Sprintf(".title %s\n", name))
	switch circuitType {
	case "rc":
		b.WriteString("V1 1 0 DC 5\n")
		b.WriteString(fmt.Sprintf("R1 1 2 %s\n", val(args, "resistance", "1k")))
		b.WriteString(fmt.Sprintf("C1 2 0 %s\n", val(args, "capacitance", "1u")))
	case "rlc":
		b.WriteString("V1 1 0 AC 1 SIN(0 1 1k)\n")
		b.WriteString(fmt.Sprintf("R1 1 2 %s\n", val(args, "resistance", "100")))
		b.WriteString(fmt.Sprintf("L1 2 3 %s\n", val(args, "inductance", "10m")))
		b.WriteString(fmt.Sprintf("C1 3 0 %s\n", val(args, "capacitance", "1u")))
	case "opamp":
		b.WriteString("Vcc 1 0 DC 15\n")
		b.WriteString("Vee 2 0 DC -15\n")
		b.WriteString("Vin 3 0 DC 0 AC 1\n")
		b.WriteString(fmt.Sprintf("R1 3 4 %s\n", val(args, "r1", "10k")))
		b.WriteString(fmt.Sprintf("Rf 4 5 %s\n", val(args, "rf", "100k")))
		b.WriteString("X1 3 2 1 5 uA741\n")
	case "transistor":
		b.WriteString("Vcc 1 0 DC 5\n")
		b.WriteString("Vin 2 0 DC 0.7\n")
		b.WriteString(fmt.Sprintf("R1 1 3 %s\n", val(args, "rc", "1k")))
		b.WriteString(fmt.Sprintf("R2 2 0 %s\n", val(args, "rb", "10k")))
		b.WriteString("Q1 3 2 0 npn\n")
	default:
		b.WriteString("V1 1 0 DC 5\n")
		b.WriteString(fmt.Sprintf("R1 1 0 %s\n", val(args, "resistance", "1k")))
	}
	analysisType := val(args, "analysis", "tran")
	switch analysisType {
	case "tran":
		b.WriteString(fmt.Sprintf(".tran 1m %s\n", val(args, "stop", "10m")))
	case "ac":
		b.WriteString(fmt.Sprintf(".ac dec 10 1 %s\n", val(args, "fmax", "1Meg")))
	case "dc":
		b.WriteString(fmt.Sprintf(".dc V1 0 5 %s\n", val(args, "step", "0.1")))
	case "op":
		b.WriteString(".op\n")
	}
	b.WriteString(".control\nrun\nprint all\n.endc\n.end\n")
	return b.String()
}

func val(args map[string]string, key, def string) string {
	if v, ok := args[key]; ok && v != "" { return v }
	return def
}
